version: '3.3' # version of compose format

services:
    landing-service:
        build: ./landing # path is relative to docker-compose.yml location
        hostname: landing-service
        ports:
            - 5050:5050 # host:container
        networks:
            sample:
                aliases:
                    - landing-service
    # Add more services below
    addition-service:
        build: ./addition
        hostname: addition-service
        ports:
            - 5051:5051
        networks:
            sample:
                aliases:
                    - addition-service
    subtraction-service:
        build: ./subtraction
        hostname: subtraction-service
        ports:
            - 5052:5052
        networks:
            sample:
                aliases:
                    - subtraction-service
    multiplication-service:
        build: ./multiplication
        hostname: multiplication-service
        ports:
            - 5053:5053
        networks:
            sample:
                aliases:
                    - multiplication-service  
    division-service:
        build: ./division
        hostname: division-service
        ports:
            - 5054:5054
        networks:
            sample:
                aliases:
                    - division-service      
    greater_than-service:
        build: ./greater_than
        hostname: greater_than-service
        ports:
            - 5055:5055
        networks:
            sample:
                aliases:
                    - greater_than-service          
    less_than-service:
        build: ./less_than
        hostname: less_than-service
        ports:
            - 5056:5056
        networks:
            sample:
                aliases:
                    - less_than-service 
    equal-service:
        build: ./equal
        hostname: equal-service
        ports:
            - 5057:5057
        networks:
            sample:
                aliases:
                    - equal-service
 
    gcd-service:
       build: ./gcd
       hostname: gcd-service
       ports:
           - 5063:5063
       networks:
           sample:
               aliases:
                   - gcd-service

    modulus-service:
        build: ./modulus
        hostname: modulus-service
        ports:
            - 5059:5059
        networks:
            sample:
                aliases:
                    - modulus-service
    exponent-service:
        build: ./exponent
        hostname: exponent-service
        ports:
            - 5060:5060
        networks:
            sample:
                aliases:
                    - exponent-service                     
    lcm-service:
        build: ./lcm
        hostname: lcm-service
        ports:
            - 5061:5061
        networks:
            sample:
                aliases:
                    - lcm-service 
networks:
    sample:

